swagger: "2.0"
info:
  version: "1.0.0"
  title: "SSE Endpoints"

host: localhost:8080
# basePath:
schemes:
  - http

tags:
  - name: Auth
    description: Auth service endpoints. localhost:50231
  - name: Product
    description: Product service endpoints. localhost:8081
  - name: Order
    description: Order service endpoints. localhost:8082
  - name: Deliveryman
    description: Deliveryman service endpoints. localhost:8083
  - name: Shipment
    description: Shipment service endpoints. localhost:8083
  - name: Location
    description: Location service endpoints. ws://localhost:9090
paths:
  /authenticate:
    post:
      tags:
        - Auth
      summary: "Authenticates user and gives back jwt token"
      description: "Authenticates user and gives back jwt token"
      parameters:
        - name: user
          in: body
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
            example:
              username: user1
              password: password1
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: {"jwt_token":"eyJhbGciOiJIUzM4N2J9.eyJzdWI1OiJhZG1pbiIsImlhdCI6MTcwMzA5MTg0OCwiZXhwIjoxNzAzMDkzNjQ4fQ.nuiDdPzdRlmL4gwUNmELOOU2nFfEAb5sg4SxsG2b62UHn6wgOhc-xReeuVzr3WI1"}
        403:
          description: "Forbidden. Bad credential"

  /products/all:
    post:
      tags:
        - Product
      summary: "Show all products."
      description: "Shows all products."
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: [
              {
                "product_name": "Product A",
                "description": "Description of Product A",
                "category": "cd",
                "brand": "A",
                "price": 50.00,
                "stock_quantity": 100,
                "supplier_id": ObjectId("5f90c393a380afd5cf0bdd1e"),
                "date_added": "ISODate('2023-01-01T08:00:00Z')"
              },
              {
                "product_name": "Product A II",
                "description": "Description of Product A II",
                "category": "Electronics",
                "brand": "B",
                "price": 21.00,
                "stock_quantity": 100,
                "supplier_id": ObjectId("5f90c393a380afd5cf0bdd1e"),
                "date_added": "ISODate('2023-01-01T08:00:00Z')"
              },
              {
                "product_name": "Product B",
                "description": "Description of Product V",
                "category": "Cd",
                "brand": "D",
                "price": 22.00,
                "stock_quantity": 32,
                "supplier_id": ObjectId("5f90c393a380afd5cf0bdd1e"),
                "date_added": "ISODate('2023-01-01T08:00:00Z')"
              }
            ]
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"

  /products/by-name:
    post:
      tags:
        - Product
      summary: "Show all products with product name."
      description: "Shows all products that contains requested name."
      parameters:
        - name: getProductsRequest
          in: body
          required: true
          schema:
            type: object
            required:
              - productName
            properties:
              productName:
                type: string
            example:
              productName: Product A
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: [
              {
                "product_name": "Product A",
                "description": "Description of Product A",
                "category": "cd",
                "brand": "A",
                "price": 50.00,
                "stock_quantity": 100,
                "supplier_id": ObjectId("5f90c393a380afd5cf0bdd1e"),
                "date_added": "ISODate('2023-01-01T08:00:00Z')"
              },
              {
                "product_name": "Product A II",
                "description": "Description of Product A II",
                "category": "Electronics",
                "brand": "B",
                "price": 21.00,
                "stock_quantity": 100,
                "supplier_id": ObjectId("5f90c393a380afd5cf0bdd1e"),
                "date_added": "ISODate('2023-01-01T08:00:00Z')"
              }
            ]
        400:
          description: "Invalid request"
          examples:
            application/json:
              {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "Invalid request content.",
                "instance": "/orders"
              }
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"
  /orders:
    post:
      tags:
        - Order
      summary: "Place a new order"
      description: "Place a new order"
      parameters:
        - name: createOrderRequest
          in: body
          required: true
          schema:
            type: object
            required:
              - customerId
              - orderDate
              - shippingAddress
              - totalAmount
              - paymentMethod
              - orderStatus
              - scheduledDelivery
              - deliveredDate
              - discounts
              - taxAmount
              - notes
              - products
            properties:
              customerId:
                type: string
                example: "32049231jf80afd5cf0bdd1e"
              orderDate:
                type: string
                example: "2023-01-01T08:00:00Z"
              shippingAddress:
                type: string
                example: "123 Main St, Cityville"
              totalAmount:
                type: number
                example: 150.00
              paymentMethod:
                type: string
                example: "Credit Card"
              orderStatus:
                type: string
                example: "Pending"
              deliveredDate:
                type: string
                example: "2023-01-02T08:00:00Z"
              scheduledDelivery:
                type: string
                example: "2023-01-02T08:00:00Z"
              discounts:
                type: number
                example: 10.00
              taxAmount:
                type: number
                example: 8.50
              notes:
                type: string
                example: "Express shipping requested"
              products:
                type: array
                items:
                  example:
                    - productId: "5f90c393a380afd5cf0bdd1c"
                      productName: "Product A"
                      quantity: 2
                      unitPrice: 50.00
                    - productId: "5f90c393a380afd5cf0bdd1d"
                      productName: "Product B"
                      quantity: 1
                      unitPrice: 50.00
      responses:
        201:
          description: "Successful response"
        400:
          description: "Invalid request"
          examples:
            application/json:
              {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "Invalid request content.",
                "instance": "/orders"
              }
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"
  /ws://localhost:9090/dm/{dmId}:
    post:

      tags:
        - Location
      summary:  Websocket to location service - get/send dm location.
      description: /dm allows sending latest location to channel, the channel is dmId

      parameters:
        - name: dmId
          in: path
          required: true
          type: integer
        - name: message
          in: body
          required: false
          description: latest location of dm.  Content type - Text
          schema:
            type: string
            example: "40.640997, -74.010685"
      responses:
        200:
          description: "location"

  /ws://localhost:9090/{dmId}:
    post:
      parameters:
        - name: dmId
          in: path
          required: true
          type: integer
      tags:
        - Location
      summary: Websocket to location service - get dm location.
      description: Allows getting the latest location of dm with {dmId}, the channel is dmId; cannot send message
      responses:
        200:
          description: "location"
  /deliverymen:
    post:
      tags:
        - Deliveryman
      summary: "Sign up a new delivery man"
      description: "Sign up a new delivery man"
      parameters:
        - name: createDeliverymanRequest
          in: body
          required: true
          schema:
            type: object
            required:
              - id
              - firstName
              - lastName
              - contactNumber
              - email
            properties:
              id:
                type: string
                example: "3204d1e"
              firstName:
                type: string
                example: "John"
              lastName:
                type: string
                example: "Doe"
              contactNumber:
                type: string
                example: "1234567890"
              email:
                type: string
                example: "john.doe@example.com"
      responses:
        201:
          description: "Successful response"
        400:
          description: "Invalid request"
          examples:
            application/json:
              {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "Invalid request content.",
                "instance": "/deliverymen"
              }
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"
  /deliverymen/all:
    post:
      tags:
        - Deliveryman
      summary: "Show all delivery men."
      description: "Shows all delivery men."
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: [
              {
                "id": 1,
                "firstName": "John",
                "lastName": "Doe",
                "contactNumber": "1234567890",
                "email": "john.doe@example.com"
              },
              {
                "id": 2,
                "firstName": "Alice",
                "lastName": "Smith",
                "contactNumber": "+9876543210",
                "email": "alice.smith@example.com"
              }
            ]
        400:
          description: "Invalid request"
          examples:
            application/json:
              {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "Invalid request content.",
                "instance": "/deliverymen/all"
              }
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"
  /shipments/all:
    post:
      tags:
        - Shipment
      summary: "Show all shipments."
      description: "Shows all shipment."
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: [
              {
                "order_id": "3",
                "deliveryman_id": ["1", "2"],
                "current_location": "123.32, 42.23"
              }
            ]
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"

  /deliverymen/by-phone-number:
    post:
      tags:
        - Deliveryman
      summary: "Show delivery men with the target phone number."
      description: "Shows delivery men with the target phone number."
      parameters:
        - name: phone_number
          in: body
          required: true
          schema:
            type: object
            required:
              - phone_number
            properties:
              phone_number:
                type: string
            example:
              phone_number: "1234567890"
      responses:
        200:
          description: "Successful response"
          examples:
            application/json: [
              {
                "id": 1,
                "firstName": "John",
                "lastName": "Doe",
                "contactNumber": "1234567890",
                "email": "john.doe@example.com"
              }
            ]
        400:
          description: "Invalid request"
          examples:
            application/json:
              {
                "type": "about:blank",
                "title": "Bad Request",
                "status": 400,
                "detail": "Invalid request content.",
                "instance": "/deliverymen/by-phone-number"
              }
        403:
          description: "Forbidden. Bad credential"
        500:
          description: "Internal server error"
