# Use an official Node.js runtime as the base image
FROM node:14 as build-stage

# Set the working directory in the Docker container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies in the Docker container
RUN npm install

# Copy the rest of the code to the working directory
COPY . .

# Expose the port that your app runs on
EXPOSE 9090

# Define the command to run your app
CMD [ "node", "location-service/location-service.js" ]


