# Use the official Node.js 14 image as the base image
FROM node:14

# Set the working directory in the Docker image to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the Docker image
COPY package*.json ./

# Install the application's dependencies
RUN npm install

# Copy the rest of the application to the Docker image
COPY ./cd-service .

# Expose port 1111
EXPOSE 1111

# Start the application
CMD [ "node", "cd-service.js" ]