name: Docker - Discovery Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Service Discovery Server - Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./service/service-discovery-server
          push: true
          tags: yankang198/service-discovery-server:latest
