name: Docker - Discovery Server

on:
  workflow_run:
    workflows: ["Main - Testing"]
    types:
      - completed
      - success

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: cd service/service-discovery-server/ && docker buildx build --platform linux/arm64 -t yankang198/service-discovery . --push

      - name: Push Docker image to DockerHub
        run: docker push yankang198/service-discovery:latest