name: Main - Testing

on:
  push:
    branches:
      - 'main'

jobs:
  artifact:
    name: Test main branch - GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.1
      - name: Gradle assemble
        run: ./gradlew clean assemble
      - name: Gradle check
        run: ./gradlew -B clean check
